feat:add films like
EvgeniyFomenko/java-filmorate pull request #5
Opened 2023-07-27 10:32 UTC by EvgeniyFomenko

feat:add user friends add

2023-07-28 07:48 UTC, alexache requested changes

2023-07-28 07:48 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/Controller.java
> +            throw new NotFoundException("Пользователь с id " + id + " не найден");
Почему пользователь?

2023-07-28 07:48 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    Set<Integer> likes = new HashSet<>();
Пропущен модификатор доступа

2023-07-28 07:48 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Integer> friendsList = new HashSet<>();
Set, который назван List?  Лучше не использовать тип списка в названии переменной

2023-07-28 07:48 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/ManageFriendsUserService.java
> +        User user1 = super.getModelById(user.getIdFrom());
Может стоит некоторые такие операции передать в сам сторадж? Потому что потом при смене вида стораджа это будет не самым оптимальным способом и потребуется изменение и сервиса, и стораджа

2023-07-28 07:48 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/ManageFriendsUserService.java
> +        List<User> lObj = new ArrayList<>();
Не очень хорошее название переменной

2023-07-28 07:48 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/ManageFriendsUserService.java
> +        Collection<? super Model> filmList = super.getModelList();
Почему это лист фильмов? И что вообще здесь происходит?

2023-07-28 07:48 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/ManageFriendsUserService.java
> +        List<User> usersList = lObj.stream().filter(e -> user.getFriendsList().contains(e.getId()))
Немного непонятная логика, можешь немного расписать? Зачем ходить по списку всех юзеров?

2023-07-28 07:48 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>  public class UserService extends ru.yandex.practicum.filmorate.service.Service {
Для чего название класса с пакетами?

2023-07-28 07:48 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryStorage.java
> +@Data
Для чего эта аннотация?

2023-07-28 07:48 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/Storage.java
> +    public <T extends Model> T get(int id);
Излишне писать модификатор доступа в интерфейсе

2023-07-28 07:48 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/service/ManageFriendsUserServiceTest.java
> +    Storage userStorage = new InMemoryUserStorage(new HashMap<>());
Не помешают модификаторы доступа

2023-08-01 14:09 UTC, EvgeniyFomenko commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>  public class UserService extends ru.yandex.practicum.filmorate.service.Service {
Так как есть аннотация Service и она совпадает по названию с моим абстрактным классом. Я попробовал импортировать нужный класс но java не понимает что к чему

2023-08-02 13:25 UTC, alexache approved these changes

2023-08-02 13:25 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/ManageFriendsUserService.java
> +        List<Integer> idFriends = user1.getIdSet().stream().filter(e -> user2.getIdSet().stream()
Наверное было бы проще просто проверять через user1.getIdSet().stream().filter(e -> user2.getIdSet().contains(e)).collect(..)

2023-08-02 13:25 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +
Не хватает @Override

2023-08-02 13:25 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public Map<Integer, ?> getModelMap() {
Зачем выдавать наружности способа хранения вовне?

2023-08-02 17:40 UTC, merged