feat:добавил поддержку базы данных
EvgeniyFomenko/java-filmorate pull request #9
Opened 2023-08-21 13:03 UTC by EvgeniyFomenko

2023-08-22 06:19 UTC, VadimZharkov commented on src/main/resources/schema.sql
> +    user2_id INTEGER REFERENCES USERS (user_id)
не особо приветствуются названия с цифрами, т.к. не несут смысловой нагрузки, лучше friend_id

2023-08-22 06:30 UTC, VadimZharkov commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS film (
как наверное уже знаешь есть два подхода к именованию таблиц, во множественном или единственном числе. те  кто пришел из джава именуют обычно во множественном, потому как это коллекция, те кто пришел из СУБД предпочитают единственное число по множеству причин, я лично встречал чаще ед. число, поэтому плюсую)

2023-08-22 06:39 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public User(int id, String name, List<Integer> friends, String email, String login, LocalDate birthday) {
Когда нужны такие конструкторы со многими параметрами джава разработчики любят использовать шаблон проектирвания builder, в lombok есть спец. аннотация `@Builder`, попробуй код станет красивей.

2023-08-22 06:42 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    public Genre(int genreId, String name) {
конструктор лишний, т.к. препроцессор lombok для `@Data` сам создаст такой

2023-08-22 06:46 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/service/Service.java
>  public abstract class Service {
Лучше класс сделать дженериком, раз у него все методы параметризированы
Service<T extends Model>

2023-08-22 07:03 UTC, VadimZharkov requested changes
Можно улучшить в части дженериков.

2023-08-22 11:06 UTC, EvgeniyFomenko commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    public Genre(int genreId, String name) {
не создаёт )

2023-08-22 11:15 UTC, EvgeniyFomenko commented on src/main/java/ru/yandex/practicum/filmorate/service/Service.java
>  public abstract class Service {
Ты прав), я подумал так как это относиться больше к валидации то засунул проверку в метод валидации ) тем самым избавился из обобощёного класса от этой конструкции )

2023-08-23 05:36 UTC, VadimZharkov approved these changes

2023-08-23 06:12 UTC, merged